"""
AgentSpace 一键配置脚本
===================
读取 SECRETS.env，自动写入所有组件的配置文件。

用法:
    python setup_secrets.py
"""
import os
import sys
from pathlib import Path

ROOT = Path(__file__).parent


def parse_secrets(env_file: Path) -> dict:
    """解析 .env 文件为字典"""
    secrets = {}
    if not env_file.exists():
        print(f"[ERROR] {env_file} 不存在！")
        sys.exit(1)

    for line in env_file.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" in line:
            key, _, value = line.partition("=")
            # 去掉行尾注释
            if " # <=" in value:
                value = value.split(" # <=")[0]
            secrets[key.strip()] = value.strip()

    return secrets


def check_required(secrets: dict) -> list[str]:
    """检查必填项，返回未填写的列表"""
    required = {
        "HUB_SERVER_IP": "服务器公网 IP",
        "GLM_API_KEY": "智谱 AI API Key (或 OPENAI_API_KEY)",
        "HUB_JWT_SECRET": "JWT 签名密钥",
        "FRP_SERVER_ADDR": "FRP 服务器地址",
        "FRP_TOKEN": "FRP 认证 Token",
        "POSTGRES_PASSWORD": "PostgreSQL 密码",
        "FRP_DASHBOARD_PASSWORD": "FRP Dashboard 密码",
    }
    missing = []
    for key, desc in required.items():
        val = secrets.get(key, "")
        if not val:
            if key == "GLM_API_KEY" and secrets.get("OPENAI_API_KEY"):
                continue
            missing.append(f"  {key} — {desc}")
    return missing


def write_hub_env(secrets: dict):
    """写入 hub/.env (Hub 服务端主配置)"""
    content = f"""# === Auto-generated by setup_secrets.py ===
# Do NOT edit — edit SECRETS.env and re-run: python setup_secrets.py

# Server
HUB_BASE_URL={secrets.get('HUB_BASE_URL', 'http://localhost:8000')}
HUB_JWT_SECRET={secrets.get('HUB_JWT_SECRET', '')}

# Database
DATABASE_URL={secrets.get('DATABASE_URL', '')}
POSTGRES_USER={secrets.get('POSTGRES_USER', 'agenthub')}
POSTGRES_PASSWORD={secrets.get('POSTGRES_PASSWORD', '')}
POSTGRES_DB={secrets.get('POSTGRES_DB', 'agent_hub')}

# Embedding
EMBEDDING_PROVIDER={secrets.get('EMBEDDING_PROVIDER', 'glm')}
GLM_API_KEY={secrets.get('GLM_API_KEY', '')}
GLM_EMBEDDING_MODEL={secrets.get('GLM_EMBEDDING_MODEL', 'embedding-3')}
OPENAI_API_KEY={secrets.get('OPENAI_API_KEY', '')}
OPENAI_EMBEDDING_MODEL={secrets.get('OPENAI_EMBEDDING_MODEL', 'text-embedding-ada-002')}

# Client
LOCAL_PORT={secrets.get('LOCAL_PORT', '8000')}
IDENTITY_PATH=identity.md
AGENTSPACE_REGION={secrets.get('AGENTSPACE_REGION', 'cn')}
TUNNEL_PROVIDER={secrets.get('TUNNEL_PROVIDER', 'frp')}

# FRP
FRP_SERVER_ADDR={secrets.get('FRP_SERVER_ADDR', '')}
FRP_SERVER_PORT={secrets.get('FRP_SERVER_PORT', '7000')}
FRP_TOKEN={secrets.get('FRP_TOKEN', '')}

# Ngrok
NGROK_AUTHTOKEN={secrets.get('NGROK_AUTHTOKEN', '')}
NGROK_REGION={secrets.get('NGROK_REGION', 'us')}

# Misc
ENV={secrets.get('ENV', 'development')}
DEBUG={secrets.get('DEBUG', 'true')}
CORS_ORIGINS={secrets.get('CORS_ORIGINS', '*')}
DEFAULT_TOP_K={secrets.get('DEFAULT_TOP_K', '3')}
SIMILARITY_THRESHOLD={secrets.get('SIMILARITY_THRESHOLD', '0.7')}
JWT_EXPIRATION_MINUTES={secrets.get('JWT_EXPIRATION_MINUTES', '10')}
"""
    target = ROOT / "hub" / ".env"
    target.write_text(content, encoding="utf-8")
    print(f"  [OK] {target}")


def write_client_env(secrets: dict):
    """写入 hub/client.env (客户端快速配置)"""
    hub_url = secrets.get("HUB_URL", f"http://{secrets.get('HUB_SERVER_IP', 'localhost')}:8000")
    content = f"""# === Auto-generated by setup_secrets.py ===
HUB_URL={hub_url}
HUB_JWT_SECRET={secrets.get('HUB_JWT_SECRET', '')}
LOCAL_PORT={secrets.get('LOCAL_PORT', '8000')}
LOCAL_HOST={secrets.get('LOCAL_HOST', '127.0.0.1')}
AGENTSPACE_REGION={secrets.get('AGENTSPACE_REGION', 'cn')}
TUNNEL_PROVIDER={secrets.get('TUNNEL_PROVIDER', 'frp')}
NGROK_AUTHTOKEN={secrets.get('NGROK_AUTHTOKEN', '')}
NGROK_REGION={secrets.get('NGROK_REGION', 'us')}
FRP_TOKEN={secrets.get('FRP_TOKEN', '')}
FRP_SERVER_ADDR={secrets.get('FRP_SERVER_ADDR', '')}
FRP_SERVER_PORT={secrets.get('FRP_SERVER_PORT', '7000')}
"""
    target = ROOT / "hub" / "client.env"
    target.write_text(content, encoding="utf-8")
    print(f"  [OK] {target}")


def write_package_env(secrets: dict):
    """写入 hub/package/.env (打包部署用)"""
    content = f"""# === Auto-generated by setup_secrets.py ===
HUB_BASE_URL={secrets.get('HUB_BASE_URL', 'http://localhost:8000')}
HUB_JWT_SECRET={secrets.get('HUB_JWT_SECRET', '')}
EMBEDDING_PROVIDER={secrets.get('EMBEDDING_PROVIDER', 'glm')}
GLM_API_KEY={secrets.get('GLM_API_KEY', '')}
GLM_EMBEDDING_MODEL={secrets.get('GLM_EMBEDDING_MODEL', 'embedding-3')}
LOCAL_PORT={secrets.get('LOCAL_PORT', '8000')}
IDENTITY_PATH=identity.md
FRP_TOKEN={secrets.get('FRP_TOKEN', '')}
FRP_SERVER_ADDR={secrets.get('FRP_SERVER_ADDR', '')}
FRP_SERVER_PORT={secrets.get('FRP_SERVER_PORT', '7000')}
NGROK_AUTHTOKEN={secrets.get('NGROK_AUTHTOKEN', '')}
NGROK_REGION={secrets.get('NGROK_REGION', 'us')}
ENV={secrets.get('ENV', 'development')}
DEBUG={secrets.get('DEBUG', 'true')}
CORS_ORIGINS={secrets.get('CORS_ORIGINS', '*')}
DEFAULT_TOP_K={secrets.get('DEFAULT_TOP_K', '3')}
SIMILARITY_THRESHOLD={secrets.get('SIMILARITY_THRESHOLD', '0.7')}
JWT_EXPIRATION_MINUTES={secrets.get('JWT_EXPIRATION_MINUTES', '10')}
"""
    target = ROOT / "hub" / "package" / ".env"
    target.write_text(content, encoding="utf-8")
    print(f"  [OK] {target}")


def write_docker_env(secrets: dict):
    """写入 hub/.env.docker (docker-compose 引用)"""
    content = f"""# === Auto-generated by setup_secrets.py ===
POSTGRES_USER={secrets.get('POSTGRES_USER', 'agenthub')}
POSTGRES_PASSWORD={secrets.get('POSTGRES_PASSWORD', '')}
POSTGRES_DB={secrets.get('POSTGRES_DB', 'agent_hub')}
HUB_JWT_SECRET={secrets.get('HUB_JWT_SECRET', '')}
OPENAI_API_KEY={secrets.get('OPENAI_API_KEY', '')}
GLM_API_KEY={secrets.get('GLM_API_KEY', '')}
HUB_BASE_URL={secrets.get('HUB_BASE_URL', 'http://localhost:8000')}
"""
    target = ROOT / "hub" / ".env.docker"
    target.write_text(content, encoding="utf-8")
    print(f"  [OK] {target}")


def main():
    print("=" * 60)
    print("  AgentSpace 一键配置")
    print("=" * 60)

    # 1. 读取
    secrets_file = ROOT / "SECRETS.env"
    print(f"\n[1/4] 读取 {secrets_file}")
    secrets = parse_secrets(secrets_file)
    print(f"  已加载 {len(secrets)} 个配置项")

    # 2. 校验
    print("\n[2/4] 检查必填项")
    missing = check_required(secrets)
    if missing:
        print("  以下必填项未配置：")
        for m in missing:
            print(m)
        print(f"\n  请编辑 {secrets_file} 后重新运行")
        sys.exit(1)
    print("  所有必填项已配置 [OK]")

    # 3. 分发
    print("\n[3/4] 分发配置到各组件")
    write_hub_env(secrets)
    write_client_env(secrets)
    write_package_env(secrets)
    write_docker_env(secrets)

    # 4. 环境变量
    print("\n[4/4] 设置当前进程环境变量")
    count = 0
    for key, value in secrets.items():
        if value:
            os.environ[key] = value
            count += 1
    print(f"  已设置 {count} 个环境变量")

    print("\n" + "=" * 60)
    print("  [OK] 配置完成！")
    print("=" * 60)
    print(f"\n  启动服务端: cd hub && python -m uvicorn hub_server.main:app --reload")
    print(f"  启动客户端: cd hub && python -m client_sdk.cli start")
    print(f"  Docker:     cd hub && docker-compose --env-file .env.docker up -d")


if __name__ == "__main__":
    main()
