"""Local skill execution engine using importlib dynamic loading.

This module provides safe, dynamic execution of locally discovered skills.
Skills are loaded on-demand from paths specified in clawhub_config.yaml,
which is generated by the DiscoveryRadar's AST scanner.
"""

from __future__ import annotations

import importlib.util
import inspect
import sys
from pathlib import Path
from typing import Any, Optional


class SkillExecutionError(Exception):
    """Raised when skill execution fails."""

    def __init__(self, skill_name: str, reason: str):
        self.skill_name = skill_name
        self.reason = reason
        super().__init__(f"Skill '{skill_name}' execution failed: {reason}")


class LocalSkillExecutor:
    """
    Execute local Python skills using dynamic module loading.

    The executor does NOT maintain a persistent registry. Instead, it loads
    skills on-demand from the config snapshot generated by DiscoveryRadar.
    This ensures complete decoupling from user code at import time.
    """

    def __init__(self, config_path: Optional[Path] = None):
        """
        Initialize the executor with a config snapshot.

        Args:
            config_path: Path to clawhub_config.yaml. If None, uses default.
        """
        self._config_path = config_path
        self._loaded_modules: dict[str, Any] = {}

    def execute(
        self,
        skill_name: str,
        skill_file_path: str,
        *,
        timeout: Optional[float] = None,
        **kwargs: Any,
    ) -> Any:
        """
        Execute a local skill by name.

        Args:
            skill_name: Name of the skill function to execute.
            skill_file_path: Path to the Python file containing the skill.
            timeout: Optional timeout in seconds (future enhancement).
            **kwargs: Arguments to pass to the skill function.

        Returns:
            The return value of the skill function.

        Raises:
            SkillExecutionError: If the skill cannot be loaded or executed.
        """
        # Load the module dynamically
        func = self._load_skill_function(skill_name, skill_file_path)

        # Validate arguments match function signature
        self._validate_arguments(func, kwargs)

        # Execute the function
        try:
            if inspect.iscoroutinefunction(func):
                # For async functions, return the coroutine for the caller to await
                return func(**kwargs)
            else:
                return func(**kwargs)
        except Exception as e:
            raise SkillExecutionError(skill_name, f"Execution error: {e}") from e

    def _load_skill_function(self, skill_name: str, file_path: str) -> Any:
        """
        Load a skill function from a Python file using importlib.

        Args:
            skill_name: Name of the skill function.
            file_path: Path to the Python file.

        Returns:
            The function object.

        Raises:
            SkillExecutionError: If loading fails.
        """
        path = Path(file_path)

        if not path.exists():
            raise SkillExecutionError(skill_name, f"File not found: {file_path}")

        # Check if already loaded (simple cache)
        module_key = str(path.resolve())
        if module_key in self._loaded_modules:
            module = self._loaded_modules[module_key]
        else:
            # Create a unique module name based on file path
            module_name = f"clawhub_skill_{path.stem}_{hash(str(path)) & 0x7fffffff}"

            try:
                # Load the module spec
                spec = importlib.util.spec_from_file_location(module_name, path)
                if spec is None or spec.loader is None:
                    raise SkillExecutionError(skill_name, f"Cannot load spec for {file_path}")

                # Create and execute the module
                module = importlib.util.module_from_spec(spec)

                # IMPORTANT: This does execute the module code, but it's necessary
                # for importlib to work. The AST scanner has already analyzed the
                # file structure, so we trust the file at this point.
                sys.modules[module_name] = module
                spec.loader.exec_module(module)

                self._loaded_modules[module_key] = module
            except Exception as e:
                raise SkillExecutionError(skill_name, f"Module loading failed: {e}") from e

        # Get the function from the module
        if not hasattr(module, skill_name):
            raise SkillExecutionError(skill_name, f"Function '{skill_name}' not found in module")

        func = getattr(module, skill_name)

        # Verify it's callable
        if not callable(func):
            raise SkillExecutionError(skill_name, f"'{skill_name}' is not a callable function")

        return func

    def _validate_arguments(self, func: Any, kwargs: dict[str, Any]) -> None:
        """
        Validate that provided arguments match the function signature.

        Args:
            func: The function to validate against.
            kwargs: Arguments that will be passed.

        Raises:
            SkillExecutionError: If arguments don't match signature.
        """
        try:
            sig = inspect.signature(func)

            # Check for unexpected arguments
            valid_params = set(sig.parameters.keys())
            provided_params = set(kwargs.keys())

            unexpected = provided_params - valid_params
            if unexpected:
                raise SkillExecutionError(
                    func.__name__,
                    f"Unexpected arguments: {', '.join(unexpected)}. "
                    f"Valid parameters: {', '.join(valid_params)}",
                )

            # Check for missing required arguments
            missing = []
            for name, param in sig.parameters.items():
                if name not in kwargs and param.default is param.empty:
                    # Skip 'self' parameter for methods
                    if name != "self":
                        missing.append(name)

            if missing:
                raise SkillExecutionError(
                    func.__name__,
                    f"Missing required arguments: {', '.join(missing)}",
                )
        except SkillExecutionError:
            raise
        except Exception as e:
            # If validation fails for any reason, log but don't block execution
            # (let the actual function call handle argument errors)
            pass

    def clear_cache(self) -> None:
        """Clear the module cache. Useful for testing or hot-reload scenarios."""
        self._loaded_modules.clear()


__all__ = ["LocalSkillExecutor", "SkillExecutionError"]
